title: Old location for Dialogporten information
email: bdl@digdir.no
description: >- # this means to ignore newlines until "baseurl:"
  Random notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elsand.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bjolan
github_username:  elsand

# Build settings
plugins:
  - jekyll-redirect-from

